apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: grafana-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grafana
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10




