apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: influxdb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: influxdb
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 2

