apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: influxdb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: influxdb
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 5
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 5


# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#  name: influxdb-hpa
# spec:
#  scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: influxdb
#  minReplicas: 1
#  maxReplicas: 5
#  metrics:
#  - type: Pods
#     pods:
#       metricName: cpu
#       targetAverageUtilization: 5
#  - type: Pods
#     pods:
#       metricName: memory
#       targetAverageUtilization: 5


